# DESCRIPTION: 
# Configuration file for the CORTO SLX interface
# This file is used to set the parameters of the NAVCAM, the rendering engine, the Blender file model and the UDP/TCP servers (recv/send).
# NOTE: Make sure the configuration matches the loaded Blender file!
# Author: Peter C., Date: 12 Jan 2025

NavCam_params:
  FOV_x: 21  # [deg], Horizontal FOV of the NAVCAM
  FOV_y: 16  # [deg], Vertical FOV of the NAVCAM
  sensor_size_x: 2048  # [pxl], Horizontal resolution of the images
  sensor_size_y: 1536  # [pxl], Vertical resolution of the images
  n_channels: 3  # [-], Number of channels of the images
  bit_encoding: 8  # [-], Number of bits per pixel
  compression: 15  # [-], Compression factor

RenderingEngine_params:
  render_engine: 'CYCLES'
  device: 'GPU'  # 'CPU' or 'GPU'
  samples: 16  # Number of samples
  diffuse_bounces: 0  # To avoid diffused light from D1 to D2. (4 default)
  tile_size: 16  # Tile size for rendering # DOUBT what does this parameter change?

BlenderModel_params:
  num_bodies: 1  # Number of bodies in the model  
  light_names: ['Light']  # Name of the sun-light in the Blender file
  bodies_names: ['Apophis'] # Names of the bodies in the Blender file 
  sun_energy: 2  # Energy value of the sun-light in Blender
  specular_factor: 0  # Specularity value for the sun-light in Blender

Server_params:
  output_path: '/home/peterc/devDir/projects-DART/rcs-1-gnc-simulator/artifacts/.tmprcs1' # Where Blender will save images
  address: "127.0.0.1"
  port_M2B: 51001  # Port from Matlab to Blender
  port_B2M: 30001  # Port from Blender to Matlab
  DUMMY_OUTPUT: false
